Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	get_data
	1

[Mon Sep 14 19:09:18 2020]
rule get_data:
    input: simulation.slim
    output: env_var.txt
    jobid: 0

[Mon Sep 14 19:09:18 2020]
Error in rule get_data:
    jobid: 0
    output: env_var.txt

RuleException:
URLError in line 9 of /Users/ecevarol/Desktop/Research/lower_threshold_project/Snakefile:
<urlopen error [Errno 2] No such file or directory: '/Users/ecevarol/Desktop/Research/lower_threshold_project/input -d out=output -d envVar=0.05 -d adjustment=0 -d L=1e4 -d thres=1'>
  File "/Users/ecevarol/opt/miniconda3/envs/snakemake/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2168, in run_wrapper
  File "/Users/ecevarol/Desktop/Research/lower_threshold_project/Snakefile", line 9, in __rule_get_data
  File "/Users/ecevarol/opt/miniconda3/envs/snakemake/lib/python3.8/urllib/request.py", line 222, in urlopen
  File "/Users/ecevarol/opt/miniconda3/envs/snakemake/lib/python3.8/urllib/request.py", line 525, in open
  File "/Users/ecevarol/opt/miniconda3/envs/snakemake/lib/python3.8/urllib/request.py", line 542, in _open
  File "/Users/ecevarol/opt/miniconda3/envs/snakemake/lib/python3.8/urllib/request.py", line 502, in _call_chain
  File "/Users/ecevarol/opt/miniconda3/envs/snakemake/lib/python3.8/urllib/request.py", line 1485, in file_open
  File "/Users/ecevarol/opt/miniconda3/envs/snakemake/lib/python3.8/urllib/request.py", line 1524, in open_local_file
  File "/Users/ecevarol/opt/miniconda3/envs/snakemake/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 529, in _callback
  File "/Users/ecevarol/opt/miniconda3/envs/snakemake/lib/python3.8/concurrent/futures/thread.py", line 57, in run
  File "/Users/ecevarol/opt/miniconda3/envs/snakemake/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 515, in cached_or_run
  File "/Users/ecevarol/opt/miniconda3/envs/snakemake/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2199, in run_wrapper
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /Users/ecevarol/Desktop/Research/lower_threshold_project/.snakemake/log/2020-09-14T190918.255756.snakemake.log
